// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Brand: typeof import('./src/components/Brand.vue')['default']
    BrandDark: typeof import('./src/components/BrandDark.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    README: typeof import('./src/components/README.md')['default']
  }
}

export { }
