// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Brand: typeof import('./src/components/Brand.vue')['default']
    BrandDark: typeof import('./src/components/BrandDark.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    Social: typeof import('./src/components/Social.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverGroup: typeof import('@headlessui/vue')['PopoverGroup']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonLogoFacebook: typeof import('virtual:vite-icons/carbon/logo-facebook')['default']
    CarbonLogoYoutube: typeof import('virtual:vite-icons/carbon/logo-youtube')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonLogoTwitter: typeof import('virtual:vite-icons/carbon/logo-twitter')['default']
    CarbonArrowRight: typeof import('virtual:vite-icons/carbon/arrow-right')['default']
  }
}

export { }
