export const members: Array<{name: string; role: string; avatar: string; twitter: string; linkedin: string; github: string}> = [
  {
    name: 'Arnab Sen',
    role: 'General Secretary',
    avatar: 'https://avatars.githubusercontent.com/u/51032928?v=4',
    twitter: 'https://twitter.com/ArnabSen1729',
    linkedin: 'https://www.linkedin.com/in/arnab-sen-b6950a194/',
    github: 'https://github.com/arnabsen1729',
  },
  {
    name: 'Sanjana Chakravarty',
    role: 'Treasurer, Women@CodeIIEST Lead',
    avatar: 'https://pbs.twimg.com/profile_images/1389488267016380419/Nm4EgRJ7_400x400.jpg',
    twitter: 'https://twitter.com/san_chotik',
    linkedin: 'https://www.linkedin.com/in/sanjana-chakravarty/',
    github: 'https://github.com/Sanjana00',
  },
  {
    name: 'Sounak Majumder',
    role: 'CP Lead, Mentor',
    avatar: 'https://i.imgur.com/XjAXtmU.png',
    twitter: '',
    linkedin: 'https://www.linkedin.com/in/sounak-majumder-45b183197/',
    github: 'https://github.com/m-sounak',
  },
  {
    name: 'Gaurav Sarkar',
    role: 'ML Lead, Mentor',
    avatar: 'https://i.imgur.com/d9Ys3aC.png',
    twitter: '',
    linkedin: 'https://www.linkedin.com/in/gaurav-sarkar05/',
    github: 'https://github.com/GauravSarkar',
  },
  {
    name: 'Sanandita Das',
    role: 'Women@CodeIIEST lead, ML team, Mentor',
    avatar: 'https://cdn.discordapp.com/attachments/860519098017251368/860519982294237184/1619587086551.jpeg',
    twitter: '',
    linkedin: 'https://www.linkedin.com/in/sanandita-das/',
    github: 'https://github.com/sanandita001',
  },
  {
    name: 'Rahul Halder',
    role: 'Dev Lead, Mentor',
    avatar: 'https://avatars.githubusercontent.com/u/48245702?v=4',
    twitter: 'https://twitter.com/hrahul2605',
    linkedin: 'https://www.linkedin.com/in/hrahul2605/',
    github: 'https://github.com/hrahul2605',
  },
  {
    name: 'Anik Das',
    role: 'Infosec Lead, Dev team, Mentor',
    avatar: 'https://avatars.githubusercontent.com/u/16396161?v=4',
    twitter: 'https://twitter.com/s02n1ck',
    linkedin: 'https://linkedin.com/in/sadn1ck',
    github: 'https://github.com/sadn1ck',
  },
  {
    name: 'Vibali Joshi',
    role: 'Dev team, Mentor',
    avatar: 'https://pbs.twimg.com/profile_images/1370332679078486017/yjHxPVA__400x400.jpg',
    twitter: 'https://twitter.com/VibaliJoshi',
    linkedin: 'https://www.linkedin.com/in/vibali-joshi-51451a115/',
    github: 'https://github.com/vibalijoshi/',
  },
  {
    name: 'Abhiroop Mukherjee',
    role: 'Youtube Channel Manager, ML Team',
    avatar: 'https://avatars.githubusercontent.com/u/69428539?s=400&u=a28addedb2747781c6feba9708fd4004a0707ef2&v=4',
    twitter: '',

    linkedin: 'https://www.linkedin.com/in/abhiroop25902/',
    github: 'https://github.com/Abhiroop25902',
  },
  {
    name: 'Sujal Modanwal',
    role: 'President of CodeChef Chapter',
    avatar: 'https://avatars.githubusercontent.com/u/68843492?v=4',
    twitter: 'https://twitter.com/ModanwalSujal',
    linkedin: 'https://www.linkedin.com/in/sujal-modanwal-2812821b4/',
    github: 'https://github.com/sujal-ux',
  },
  {
    name: 'Anish De',
    role: 'CP Lead of CodeChef Chapter, CP team, Mentor',
    avatar: 'https://avatars.githubusercontent.com/u/59112660?v=4',
    twitter: 'https://twitter.com/AnishDe10',
    linkedin: 'https://www.linkedin.com/in/anish-de-1b090a193/',
    github: 'https://github.com/Anishde85',
  },
  {
    name: 'Jyoti Anjaly',
    role: 'Outreach & Media Lead of CodeChef Chapter',
    avatar: 'https://media-exp3.licdn.com/dms/image/C4D03AQFGBl3GmwJHTw/profile-displayphoto-shrink_400_400/0/1622210930383?e=1630540800&v=beta&t=Cb_FEFT1_JH0Xo33mvTZ-hkeznIgxUZY5gcM5RYomrM',
    twitter: 'https://twitter.com/jyotianjaly',
    linkedin: 'https://www.linkedin.com/in/jyoti-anjaly-1979651b3/',
    github: 'https://github.com/jyoti-anjaly',
  },
  {
    name: 'Krishnendu Bera',
    role: 'Dev team',
    avatar: 'https://avatars.githubusercontent.com/u/51166937?s=400&u=0cf419bcffc38af5d2e71d920b63b0c27022e71a&v=4',
    twitter: 'https://twitter.com/BKrishnendu63',
    linkedin: 'https://www.linkedin.com/in/krishnendu-bera-b294b5164/',
    github: 'https://github.com/berakrishnendu36/',
  },
  {
    name: 'Dwaipayan Ray',
    role: 'Veteran',
    avatar: 'https://avatars.githubusercontent.com/u/35661311?v=4',
    twitter: 'https://twitter.com/RayDwaipayan',
    linkedin: 'https://www.linkedin.com/in/dwaipayan-ray/',
    github: 'https://github.com/raydwaipayan',
  },
  {
    name: 'Shivam Kumar Singh',
    role: 'Veteran',
    twitter: '',
    avatar: 'https://avatars.githubusercontent.com/u/47945055?v=4',
    linkedin: 'https://www.linkedin.com/in/shivamhere/',
    github: 'https://github.com/shivam-51',
  },
  {
    name: 'Narapurredy Srikanth',
    role: 'Veteran',
    twitter: '',
    avatar: 'https://avatars.githubusercontent.com/u/63089621?v=4',
    linkedin: 'https://www.linkedin.com/in/narapureddy-srikanth/',
    github: 'https://github.com/Narapureddy-Srikanth',
  },
  {
    name: 'Sarbik Betal',
    role: 'Veteran',
    avatar: 'https://avatars.githubusercontent.com/u/41508422?v=4',
    twitter: 'https://twitter.com/Srbk55',
    linkedin: 'https://www.linkedin.com/in/sarbikbetal/',
    github: 'http://github.com/sarbikbetal',
  },
  {
    name: 'Rajdeep Ghosh',
    role: 'Dev team',
    avatar: 'https://avatars.githubusercontent.com/u/58541505?v=4',
    twitter: 'https://twitter.com/Rajdeep57931085',
    linkedin: 'https://www.linkedin.com/in/rajdeep-ghosh2000rg/',
    github: 'https://github.com/Rajdeep-G',
  },

  {
    name: 'Abhinaba Chowdhury',
    role: 'Events Lead of CodeChef Chapter',
    avatar: 'https://avatars.githubusercontent.com/u/59314943?v=4',
    twitter: '',
    linkedin: 'https://www.linkedin.com/in/abhichowdhury7721',
    github: 'https://github.com/AbhiC7721',
  },
  {
    name: 'Manish Kundu',
    role: 'CP Team ',
    avatar: 'https://avatars.githubusercontent.com/u/35730135?v=4',
    twitter: 'https://twitter.com/mkmanish17',
    linkedin: 'https://www.linkedin.com/in/manishkundu17',
    github: 'https://github.com/iammanish17',
  },
  {
    name: 'Priyanshi Agarwal',
    role: 'CP Team',
    avatar: 'https://pbs.twimg.com/profile_images/1363153542991646726/TTqwWoYQ_400x400.jpg',
    twitter: 'https://twitter.com/priyanshi3008',
    linkedin: 'https://www.linkedin.com/in/priyanshi-agarwal-3008/',
    github: 'https://github.com/priyanshi-3008',
  },
  {
    name: 'Neeraj Pratap Hazarika',
    role: 'Video Editor',
    avatar: 'https://avatars.githubusercontent.com/u/72177954?s=60&v=4',
    twitter: '',
    linkedin: 'https://www.linkedin.com/in/neeraj-pratap-hazarika-8800301b8/',
    github: 'https://github.com/NeerajHazarika',
  },
  {
    name: 'Devanshu Chatterjee',
    role: 'Video Editor',
    avatar: 'https://avatars.githubusercontent.com/u/78012571?s=400&u=b497b61c1dcdd0ed5b2b5c0f602bcef4698ee097&v=4',
    twitter: '',
    linkedin: 'https://www.linkedin.com/in/devanshu-chatterjee-517645200/',
    github: 'https://github.com/01-dc',
  },
]
